/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Guacha
 */
public class Registro extends javax.swing.JFrame {

    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }
    
    
    private String conv(char[] chr){
        String res = "";
        
        for (int i = 0; i < chr.length; i++){
            res = res + chr[i];
        }
        return res;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usr = new javax.swing.JTextField();
        conpss = new javax.swing.JPasswordField();
        pss = new javax.swing.JPasswordField();
        salir = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(442, 372));
        setMinimumSize(new java.awt.Dimension(442, 372));
        setPreferredSize(new java.awt.Dimension(442, 372));
        getContentPane().setLayout(null);

        usr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrActionPerformed(evt);
            }
        });
        getContentPane().add(usr);
        usr.setBounds(210, 60, 150, 30);

        conpss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conpss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpssActionPerformed(evt);
            }
        });
        getContentPane().add(conpss);
        conpss.setBounds(210, 140, 150, 30);

        pss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssActionPerformed(evt);
            }
        });
        getContentPane().add(pss);
        pss.setBounds(210, 100, 150, 30);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/base5.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salirMouseReleased(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(140, 280, 170, 40);

        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/base4.png"))); // NOI18N
        reg.setBorderPainted(false);
        reg.setContentAreaFilled(false);
        reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                regMouseReleased(evt);
            }
        });
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg);
        reg.setBounds(160, 220, 130, 40);

        jLabel1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel1.setText("Confirmar contraseña");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 140, 120, 20);

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 120, 20);

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel3.setText("Nombre de usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 60, 120, 20);

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registro");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 10, 450, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/RegisterBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-220, -260, 670, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Main f = new Main();
        this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void pssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssActionPerformed
        
    }//GEN-LAST:event_pssActionPerformed

    private void usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrActionPerformed

    private void conpssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpssActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        char[] psw = pss.getPassword();
        char[] psw2 = conpss.getPassword();
        String usuario = usr.getText();
        if (conv(psw2).equals(conv(psw))){
            
            
            dbclass regusr = new dbclass("src/files/usr.txt", true);
            dbclass regpsw = new dbclass("src/files/psw.txt", true);
            
            try {
                if (regusr.compArch(usuario)){
                    JOptionPane.showMessageDialog(null, "El usuario " + usuario + " Ya se encuentra registrado, Inténte con otro nombre.", "Error de registro", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        regusr.escrArch(usuario);
                        regpsw.escrArch(conv(psw));
                        JOptionPane.showMessageDialog(null, "El usuario " + usuario + " ha sido registrado satisfactoriamente", "Registro Satisfactorio", JOptionPane.INFORMATION_MESSAGE);
                        
                        Main vent = new Main();
                        vent.setVisible(true);
                        this.dispose();
                    } catch (IOException ex) {
                        System.out.println("ERROR DE ESCRITURA!");
                        System.out.println("Tipo de Error: " + ex);
                        System.out.println("Contacte a Servicio técnico");
                    }
                }
            } catch (IOException ex) {
                try {
                    regusr.escrArch(usuario);
                    regpsw.escrArch(conv(psw));
                    JOptionPane.showMessageDialog(null, "El usuario " + usuario + " ha sido registrado satisfactoriamente", "Registro Satisfactorio", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ex1) {
                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
            
        } else{
            JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden, Inténte nuevamente", "Error de registro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_regActionPerformed

    private void regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/tilted4.png"));
        reg.setIcon(ii);
    }//GEN-LAST:event_regMouseEntered

    private void regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/base4.png"));
        reg.setIcon(ii);
    }//GEN-LAST:event_regMouseExited

    private void regMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMousePressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/pressed4.png"));
        reg.setIcon(ii);
    }//GEN-LAST:event_regMousePressed

    private void regMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseReleased
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/base4.png"));
        reg.setIcon(ii);
    }//GEN-LAST:event_regMouseReleased

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/tilted5.png"));
        salir.setIcon(ii);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/base5.png"));
        salir.setIcon(ii);
    }//GEN-LAST:event_salirMouseExited

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/pressed5.png"));
        salir.setIcon(ii);
    }//GEN-LAST:event_salirMousePressed

    private void salirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseReleased
        ImageIcon ii = new ImageIcon(getClass().getResource("/Buttons/base5.png"));
        salir.setIcon(ii);
    }//GEN-LAST:event_salirMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conpss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pss;
    private javax.swing.JButton reg;
    private javax.swing.JButton salir;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
