/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;





/**
 *
 * @author galea
 */
public class Victory extends javax.swing.JFrame {

    /**
     * Creates new form Victory
     */
    public Victory(){
        initComponents();
    }
    public Victory(int winner) {
        initComponents();
        gamemec mec = new gamemec();
        int wh = mec.getblanc(), bl = mec.getnoir();
        temps.setText(mec.getTime());
        fichas.setText(String.valueOf(mec.contFich()));
        if (winner  == bl) {
           txt.setText("winner winner chicken dinner (Negras)");
           omedetou.setText("黒いさん、おめでとうございます！！");
        } else{
            txt.setText("winner winner chicken dinner (Blancas)");
            omedetou.setText("白いさん、おめでとうございます！！");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt = new javax.swing.JLabel();
        omedetou = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fichas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        temps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(329, 106));
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Volver a jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 210, 190, 30);

        txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt.setLabelFor(txt);
        txt.setText("winner winner chicken dinner");
        txt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(txt);
        txt.setBounds(0, 10, 500, 44);
        txt.getAccessibleContext().setAccessibleParent(txt);

        omedetou.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 24)); // NOI18N
        omedetou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        omedetou.setText("黒さん、おめでとうございます！！");
        getContentPane().add(omedetou);
        omedetou.setBounds(1, 86, 500, 30);

        jButton2.setText("Volver al menú Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 210, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Fichas Colocadas: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 160, 140, 20);

        fichas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fichas.setText("fichas");
        getContentPane().add(fichas);
        fichas.setBounds(290, 160, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Tiempo de partida: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 140, 150, 20);

        temps.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        temps.setText("temps");
        getContentPane().add(temps);
        temps.setBounds(290, 140, 70, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inises vent = new inises();
        vent.setVisible(true);
        this.dispose();
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Main vent = new Main();
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Victory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Victory().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fichas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel omedetou;
    private javax.swing.JLabel temps;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
